language: node_js
node_js:
     - "8"
cache: npm
before_script:
     - npm install -g gulp-cli
script: gulp deploy
deploy:
     provider: pages
     skip-cleanup: true
     github-token: $GITHUB_TOKEN
     keep-history: true
     on:
          branch: master